PRIYANKA MURUGAN

TRACK: DATA ANALYTICS

LEVEL 1(TASK 3): CLEANING DATASETS

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv("/content/dirty_zomato_200_rows.csv")

In [ ]:
df.head(5)

,Order_ID,Date,Food_Item,Quantity,Total_Price,Customer_Type,Feedback,Discount,Location
0,ZM-1001,2025-06-13,Butter Chicken,3,546,RETURNING,NaN,NaN,Delhi
1,ZM-1002,2025-01-24,Dosa,15,5932,RETURNING,Poor,10.0,Nagpur
2,ZM-1003,2025-01-02,Fried Rice,3,573,NEW,Excellent,0.0,Kolkata
3,ZM-1004,04/06/2025,Butter Chicken,4,1028,Returning,Excellent,NaN,Bangalore
4,ZM-1005,2025/04/03,Dosa,1,131,NEW,Excellent,10.0,Delhi

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       210 non-null    object
 1   Date           210 non-null    object
 2   Food_Item      210 non-null    object
 3   Quantity       210 non-null    int64
 4   Total_Price    210 non-null    int64
 5   Customer_Type  182 non-null    object
 6   Feedback       196 non-null    object
 7   Discount       167 non-null    float64
 8   Location       210 non-null    object
dtypes: float64(1), int64(2), object(6)
memory usage: 14.9+ KB

In [ ]:
df.sample()

,Order_ID,Date,Food_Item,Quantity,Total_Price,Customer_Type,Feedback,Discount,Location
85,ZM-1086,25/06/2025,Dosa,1,231,RETURNING,Excellent,50.0,Pune

In [ ]:
df.isnull().sum()

Order_ID          0
Date              0
Food_Item         0
Quantity          0
Total_Price       0
Customer_Type    28
Feedback         14
Discount         43
Location          0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(10)

In [ ]:
df.drop_duplicates()

,Order_ID,Date,Food_Item,Quantity,Total_Price,Customer_Type,Feedback,Discount,Location
0,ZM-1001,2025-06-13,Butter Chicken,3,546,RETURNING,NaN,NaN,Delhi
1,ZM-1002,2025-01-24,Dosa,15,5932,RETURNING,Poor,10.0,Nagpur
2,ZM-1003,2025-01-02,Fried Rice,3,573,NEW,Excellent,0.0,Kolkata
3,ZM-1004,04/06/2025,Butter Chicken,4,1028,Returning,Excellent,NaN,Bangalore
4,ZM-1005,2025/04/03,Dosa,1,131,NEW,Excellent,10.0,Delhi
...,...,...,...,...,...,...,...,...,...
195,ZM-1196,2025/04/19,Fried Rice,2,366,NaN,Average,10.0,Delhi
196,ZM-1197,2025-06-07,Dosa,2,274,New,NaN,NaN,Mumbai
197,ZM-1198,2025-04-23,Pasta,2,626,New,Good,NaN,Bangalore
198,ZM-1199,28/05/2025,Sandwich,5,1585,NEW,Good,20.0,Pune
199,ZM-1200,16/04/2025,Pizza,1,262,NaN,Good,50.0,Nagpur

In [ ]:
df.dtypes

Order_ID          object
Date              object
Food_Item         object
Quantity           int64
Total_Price        int64
Customer_Type     object
Feedback          object
Discount         float64
Location          object
dtype: object

In [ ]:
df = df.apply(lambda col: col.str.strip() if col.dtype == "object" else col)

In [ ]:
df["Customer_Type"] = df["Customer_Type"].str.upper()

In [ ]:
df["Feedback"] = df["Feedback"].str.title()

In [ ]:
df["Location"] = df["Location"].str.title()

In [ ]:
df["Date"] = pd.to_datetime(df["Date"], format="mixed")
df["Date"] = df["Date"].dt.strftime("%Y-%m-%d")

In [ ]:
df["Customer_Type"] = df["Customer_Type"].fillna(df["Customer_Type"].mode()[0])
df["Feedback"] = df["Feedback"].fillna("No Feedback")
df["Discount"] = df["Discount"].fillna(0)

In [ ]:
df.isnull().sum()

Order_ID         0
Date             0
Food_Item        0
Quantity         0
Total_Price      0
Customer_Type    0
Feedback         0
Discount         0
Location         0
dtype: int64

In [ ]:
df.head(5)

,Order_ID,Date,Food_Item,Quantity,Total_Price,Customer_Type,Feedback,Discount,Location
0,ZM-1001,2025-06-13,Butter Chicken,3,546,RETURNING,No Feedback,0.0,Delhi
1,ZM-1002,2025-01-24,Dosa,15,5932,RETURNING,Poor,10.0,Nagpur
2,ZM-1003,2025-01-02,Fried Rice,3,573,NEW,Excellent,0.0,Kolkata
3,ZM-1004,2025-04-06,Butter Chicken,4,1028,RETURNING,Excellent,0.0,Bangalore
4,ZM-1005,2025-04-03,Dosa,1,131,NEW,Excellent,10.0,Delhi